<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Version>1.1.0</Version>
    <Authors>Dmitry Nikulshin</Authors>
    <Copyright>Copyright © 2023 Dmitry Nikulshin</Copyright>
    <PackageProjectUrl>https://github.com/DmitryNikulshin/LogoffUsersTool</PackageProjectUrl>
    <RepositoryUrl>https://github.com/DmitryNikulshin/LogoffUsersTool</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
